---

- name: postgres
  apt: name={{ item }}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
  sudo: yes

- name: Make sure its running
  service: name=postgresql state=started enabled=yes
  sudo: yes

- postgresql_user: name=vagrant password=password role_attr_flags=CREATEDB,NOSUPERUSER
  sudo_user: postgres

- postgresql_db:
    name=countdown
    encoding='UTF-8'
    template='template0'
    owner='vagrant'
  sudo_user: postgres
